# Railway.app deployment configuration

[build]
command = "npm run build"

[deploy]
startCommand = "npm start"

# Environment variables needed:
# NEXT_PUBLIC_SUPABASE_URL (required)
# NEXT_PUBLIC_SUPABASE_ANON_KEY (required)
# SUPABASE_SERVICE_ROLE_KEY (optional)
# TELEGRAM_BOT_TOKEN (optional)
# OPENAI_API_KEY (optional)
# PORT (automatically set by Railway)