# Railway.app deployment configuration

[build]
command = "npm run build"

[deploy]
startCommand = "npm start"

# Environment variables needed:
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY (optional)
# TELEGRAM_BOT_TOKEN (optional)
# OPENAI_API_KEY (optional)

[env]
PORT = "3000"