# Railway.app deployment configuration

# Switch to Docker build since it works locally
[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"

# IMPORTANT: You must set these environment variables in your Railway project settings
# Required environment variables:
# - NEXT_PUBLIC_SUPABASE_URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY
#
# Optional environment variables:
# - SUPABASE_SERVICE_ROLE_KEY
# - TELEGRAM_BOT_TOKEN
# - OPENAI_API_KEY

[env]
PORT = "3000"