name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase local instance
        run: |
          supabase start

      - name: Verify migrations can be applied
        run: |
          supabase db reset --debug

      - name: Check migration status
        run: |
          supabase migration list

      - name: Generate types and verify
        run: |
          supabase gen types typescript --local > src/types/database.ts
          git diff --exit-code src/types/database.ts || echo "Types need to be regenerated"

      - name: Stop Supabase
        if: always()
        run: |
          supabase stop